api/meetup/urls.py
from django.urls import path

from . import views

app_name = 'meetup'

urlpatterns = [
    path('list/', views.MeetupAdd.as_view(), name='list'),
    path('list_page/', views.MeetupModuleList.as_view(), name='list_page'),
    path('create/', views.MeetupAdd.as_view(), name='create'),
    path('update/<int:pk>', views.MeetupModuleDetail.as_view(), name='update'),
    path('get_meetup/<int:pk>', views.MeetupModuleDetail.as_view(), name='get_meetup'),
    path('delete/<int:pk>', views.MeetupModuleDetail.as_view(), name='delete'),

]

api/urls.py
# coding=utf-8
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers

router = routers.DefaultRouter()

app_name = "api"

urlpatterns = [

    url(r'^', include(router.urls)),
    path('meetup/', include('api.meetup.urls')),
    path('meetup_enroll_invite_users/', include('api.meetup_enroll_invite_users.urls')),
    path('registration_check_in_user/', include('api.registration_check_in_user.urls')),
    path('check_weather/', include('api.check_weather.urls')),
    path('notification/', include('api.notification.urls')),
    path('user/', include('api.user.urls')),

]

app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from meetup.views import Index

urlpatterns = [
    url(r"^", include("meetup.urls"), name="meetup"),
    path('admin/', admin.site.urls),
    url(r"^api/", include("api.urls"), name="api"),
]

meetup/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views

app_name = 'meetup'

urlpatterns = [
    url(r"^$", views.Index.as_view(), name="index"),
    url(r"logout/$", views.logout, name="logout"),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^dashboard', views.Dashboard.as_view(), name='dashboard'),
    url(r'^check_in', views.RegistrationUser.as_view(), name='check_in'),
    url(r'^create_meeetup_beer', views.CreateMeeetupBeer.as_view(), name='create_meeetup_beer'),
    url(r'^notification_all', views.NotificationAll.as_view(), name='notification_all'),
]

api/meetup/views.py
from datetime import datetime

from rest_framework import status, generics
from rest_framework.authentication import TokenAuthentication, SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api.common import Pagination
from core.models import Meetup

from api.meetup.serializers import MeetupSerializers


class MeetupAdd(APIView):

    """
        ``GET`` lists all  Meetups


         see :doc:`Flexible Security Framework `.

         **Example request**:

        .. code-block:: http

            GET  api/meetup/list/

        **Example response**:

        .. code-block:: json

             [
                {
                    "id": 1,
                    "name": "hola",
                    "date": "2020-10-28T06:00:00Z",
                    "description": "",
                    "count_beer": 0,
                    "maximum_temperature": 0.0,
                    "count_participants": 0,
                    "direction": "fasdasdf"
                }
            ]

        .. code-block:: http

            POST  api/meetup/create/
            :parameter
            {
                "name": [
                    "This field may not be blank."
                ],
                "date": [
                    "Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]."
                ],
                "direction": [
                    "This field may not be blank."
                ]
            }

            **Example response**:

            .. code-block:: json parameter required

                 {
                    'user': self.user.pk,
                    'date': '2020-01-02 00:00:00',
                    'name': 'Meetup Beer2',
                    'description': 'Description Meetup2',
                    'count_beer': 36,
                    'maximum_temperature': 30.0,
                    'count_participants': 10,
                    'direction': "Avenida siempre viva 225"
                }

    """

    authentication_classes = [
        SessionAuthentication,
        BasicAuthentication,
        TokenAuthentication,
    ]
    permission_classes = (IsAuthenticated,)

    serializer_class = MeetupSerializers

    def get(self, request, format=None):
        """List all Meetup"""
        user_id = self.request.GET.get('user_id', -1)
        meetup = Meetup.objects.all()

        serializer = MeetupSerializers(meetup, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        """List create a new Meetup."""
        serializer = MeetupSerializers(data=request.data)

        try:
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.initial_data, status=status.HTTP_201_CREATED)
        except Exception as error:
            errors = error.args[0]
            return Response({'error': errors}, content_type="application/json", status=status.HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class MeetupModuleDetail(APIView):
    """
        retrieve:
            Return the given the Meetup
            GET api/meetup/get_meetup/1

        Update:
            update a Meetup
            PUT api/meetup/update/1
            :parameter
                {
                    "name": [
                        "This field is required."
                    ],
                    "date": [
                        "This field is required."
                    ],
                    "direction": [
                        "This field is required."
                    ]
                }
                Exmple json:
                {
                    'user': 1,
                    'meetup': 1,
                    'user_check_in': True
                }

        Delete:
            delete a Meetup instance.
            DELETE api/meetup/delete/1
    """

    def get_object(self, pk):
        try:
            object = Meetup.objects.get(pk=pk)
            return object
        except Meetup.DoesNotExist:
            from django.http import Http404
            raise Http404

    def get(self, request, pk, format=None):
        """Return detail of the meetup"""
        file_obj = self.get_object(pk)
        serializer = MeetupSerializers(file_obj)

        return Response(serializer.data)

    def put(self, request, pk, format=None):
        """Update meetup"""
        instance = self.get_object(pk)
        serializer = MeetupSerializers(instance, data=request.data)
        try:
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Exception as error:
            errors = error.args[0]

    def delete(self, request, pk, format=None):
        """Delete meetup"""
        meetup = self.get_object(pk)
        meetup.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class MeetupModuleList(generics.ListAPIView):
    """
        retrieve:
            Return list of meetup on pagination
            Example:
                {
                    "prev_page_url": null,
                    "from": 1,
                    "to": 1,
                    "total": 1,
                    "per_page": 1,
                    "current_page": 1,
                    "last_page": 1,
                    "next_page_url": null,
                    "data": [
                        {
                            "id": 1,
                            "name": "hola",
                            "date": "2020-10-28T06:00:00Z",
                            "description": "",
                            "count_beer": 0,
                            "maximum_temperature": 0.0,
                            "count_participants": 0,
                            "direction": "fasdasdf"
                        }
                    ]
                }
    """

    authentication_classes = [
        SessionAuthentication,
        BasicAuthentication,
        TokenAuthentication,
    ]
    permission_classes = (IsAuthenticated,)

    serializer_class = MeetupSerializers
    pagination_class = Pagination

    def get_queryset(self):
        """Return list of meetup on pagination"""
        filter = self.request.GET.get('filter', None)
        sort = self.request.GET.get('sort', None)
        sort_file = 'id'
        if sort is not None:
            sort = self.request.GET['sort'].split('|')
            if sort[1] == 'desc':
                sort_file = f"{sort[0]}"
            else:
                sort_file = f"-{sort[0]}"

        if filter is not None:
            if filter.isnumeric():
                files = Meetup.objects.filter(
                    id=filter
                )
            else:
                files = Meetup.objects.filter(
                    name__contains=filter
                ) | Meetup.objects.filter(
                    direction__contains=filter
                ).order_by(sort_file)
        else:
            files = Meetup.objects.get_queryset().order_by(sort_file)
        return files

    def is_date(self, date_text):
        try:
            if len(date_text[:10]) == 10 and date_text[:10] != datetime.strptime(date_text[:10], "%Y-%m-%d").strftime('%Y-%m-%d'):
                raise ValueError
            return True
        except ValueError:
            return False

meetup/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth import logout as do_logout


@login_required
def index(request):

    return render(request, 'index.html',)


class Index(LoginRequiredMixin, TemplateView):
    template_name = "blank.html"

    def get_context_data(self, *args, **kwargs):
       pass

    def get(self, request, *args, **kwargs):
        context = {
            'action': "true",
        }

        return render(request, 'dashboard/dashboard.html', context)


def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('/')


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "blank.html"

    def get_context_data(self, *args, **kwargs):
       pass

    def get(self, request, *args, **kwargs):

        context = {
            'action': "true",
        }
        return render(request, 'dashboard/dashboard.html', context)


class RegistrationUser(LoginRequiredMixin, TemplateView):
    template_name = "blank.html"

    def get_context_data(self, *args, **kwargs):
        pass

    def get(self, request, *args, **kwargs):

        context = {
            'action': "false",
        }

        return render(request, 'dashboard/dashboard.html', context)


class CreateMeeetupBeer(LoginRequiredMixin, TemplateView):
    template_name = "blank.html"

    def get_context_data(self, *args, **kwargs):
        pass

    def get(self, request, *args, **kwargs):

        return render(request, 'create_meeetup_beer/create_meeetup_beer.html')


class NotificationAll(LoginRequiredMixin, TemplateView):
    template_name = "blank.html"

    def get_context_data(self, *args, **kwargs):
        pass

    def get(self, request, *args, **kwargs):

        return render(request, 'notification/notification.html')

meetup/templates/base_admin.html
{% load staticfiles %}
{% load i18n %}
{% load filter_menu %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="description" content="">

    <!-- Open Graph Meta-->
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Suite Intellignos">
    <meta property="og:title" content="Suite Intellignos Administration">
    <title>Meetup beer</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
     <!-- Font-icon css-->
    {% block stylesheets %}

    {% endblock stylesheets %}

    {% load static %}
      <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
      <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="{% static '/css/notify.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
  </head>
  <body class="app sidebar-mini rtl">
    {% csrf_token %}
    <!-- Navbar-->
    <header class="app-header">
      <a class="app-header__logo" href="/">
        <img src="{% static '/img/log_beer.jpg' %}" style="width: 227px;height: 62px;" class="logoD full">
      </a>
      <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
      <!-- Navbar Right Menu-->
      <ul class="app-nav">
        <!--Notification Menu-->
        <div id="app_notification">
             <notifications></notifications>
        </div>

        <!-- User Menu-->
        <li class="dropdown">
          <a class="app-nav__item" href="{% url 'meetup:logout' %}" >
            <i class="fa fa-sign-out fa-lg"></i>Logout
          </a>

        </li>
      </ul>

    </header>
    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <div class="app-sidebar__user">
          <img class="app-sidebar__user-avatar" src="{% static '/img/avatar.jpg' %}" alt="User Image">
        <div>
          <p class="app-sidebar__user-name">{{ user.lastname }} {{ user.name }}</p>
          <p class="app-sidebar__user-designation"></p>
        </div>
      </div>
      <ul class="app-menu">
        <li>
          <a id="dashboard" class="app-menu__item active"
             href="{% url 'meetup:dashboard' %}">
            <i class="app-menu__icon fa fa-dashboard"></i>
            <span class="app-menu__label">Dashboard</span>
          </a>
        </li>
        {% if request.user.is_superuser %}
          <li>
              <a class="app-menu__item" id="create_meetup_beer" href="{% url 'meetup:create_meeetup_beer' %}">
                <i class="app-menu__icon fa fa-file-text"></i>
                <span class="app-menu__label">Create Meetup beer</span>
              </a>
          </li>
        {% endif %}

        <li>
            <a class="app-menu__item" id="check_in" href="{% url 'meetup:check_in' %}">
              <i class="app-menu__icon fa fa-pie-chart"></i>
              <span class="app-menu__label">list of registered meetups</span>
            </a>
        </li>




      </ul>
    </aside>
    <div id="app_content">
         <loading></loading>
    </div>
    <main class="app-content">

      {% block content %}
        <div class="app-title">
          <div>
            <h1><i class="fa fa-dashboard"></i> {% trans 'Dashboard' %}</h1>

          </div>
          <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item"><a href="#">{% trans 'Dashboard' %}</a></li>
          </ul>
        </div>
        <div class="row">

        </div>

      {% endblock %}
    </main>
     <!-- Essential javascripts for application to work-->
    <script src="{% static '/js/plugins/vue.js' %}"></script>
    <script src="{% static '/js/plugins/vuex.js' %}"></script>
    <script src="{% static '/js/plugins/axios.js' %}"></script>
    <script src="{% static '/js/plugins/vee-validate.js' %}"></script>
    <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static '/js/plugins/popper.min.js' %}"></script>
    <script src="{% static '/js/plugins/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/plugins/notify.js' %}"></script>
    <script src="{% static '/js/plugins/uiv.js' %}"></script>
    <script src="{% static '/js/main.js' %}"></script>
    <script src="{% static '/js/plugins/moment.min.js' %}"></script>
    <script src="{% static '/js/plugins/v-tooltip.min.js' %}"></script>


    <!-- The javascript plugin to display page loading on top-->
    <script src="{% static '/js/plugins/pace.min.js' %}"></script>

    <!-- Google analytics script-->
    <script type="text/javascript">
      const API_PREFIX = '{{ API_PREFIX }}';
      const URL_STATIC = '/static/';
      const CRFTOKEN = $("input[name*='csrfmiddlewaretoken']").val();
      const PRODUCCION = '{{ PRODUCCION }}';
      const TYPE_USER = '{{ TYPE_USER }}';
      const USER_ID = '{{ USER_ID }}';
      const NOTIFICATION_URL = '{% url 'meetup:notification_all' %}';

      if(document.location.hostname == 'pratikborsadiya.in') {
      	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      	ga('create', 'UA-72504830-1', 'auto');
      	ga('send', 'pageview');
      }
    </script>

    <script src="{% static '/js/common/loading.js' %}"></script>
    <script src="{% static '/js/common/utils.js' %}"></script>
    <script src="{% static '/js/common/store.js' %}"></script>
    <script src="{% static '/js/common/app_content.js' %}"></script>
    <script src="{% static '/js/notification/notifications.js' %}"></script>
    {% block javascripts %}
    {% endblock javascripts %}

  </body>
</html>

meetup/templates/index.html
{% extends 'base_admin.html' %}